# Generated by Django 4.2.9 on 2026-01-15 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('psyexp', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('fields_map', models.JSONField(blank=True, default=dict)),
                ('summary_fields_map', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('site', models.CharField(blank=True, max_length=200)),
                ('operator', models.CharField(blank=True, max_length=200)),
                ('session_type', models.CharField(blank=True, max_length=50)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('exp_version', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('frontmatter', models.JSONField(blank=True, default=dict)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mindtrace.patient')),
                ('protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='mindtrace.protocol')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, max_length=200)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('pagelink', models.TextField(blank=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='mindtrace.assessment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_runs', to='mindtrace.session')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoring', models.CharField(choices=[('unknown', 'unknown'), ('binary', 'binary'), ('ordinal', 'ordinal'), ('svr', 'svr'), ('qab', 'qab'), ('demographics', 'demographics'), ('fluent_speech', 'fluent_speech'), ('subscale', 'subscale'), ('praxis', 'praxis')], default='unknown', max_length=32)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='mindtrace.assessment')),
                ('categories', models.ManyToManyField(blank=True, related_name='assessments', to='mindtrace.category')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, unique=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='mindtrace.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='ProtocolAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_protocols', to='mindtrace.assessment')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_assessments', to='mindtrace.protocol')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('protocol', 'assessment')},
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('value_text', models.TextField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='mindtrace.assessmentrun')),
            ],
            options={
                'indexes': [models.Index(fields=['key'], name='mindtrace_m_key_b45b20_idx')],
                'unique_together': {('run', 'key', 'value_text')},
            },
        ),
    ]
